#!/bin/bash

# Copyright (C) 2026 Nikos Mavrogiannopoulos
#
# License: BSD

srcdir="${srcdir:-.}"

echo "===== radcli2 avp codec / FreeRADIUS interoperability ====="
echo " 1. User-Password (RFC 2865 5.2) encryption is accepted by a"
echo "    real FreeRADIUS server, and its Access-Accept decodes correctly"
echo " 2. radcli_avp_decode() correctly reverses Tunnel-Password and"
echo "    MS-MPPE-Send-Key/Recv-Key salt-encryption (RFC 2868/2548) as"
echo "    actually generated by FreeRADIUS, not just by this codec itself"
echo "============================================================="
echo "This test will use a radius server on localhost"
echo "and which can be executed with ns.sh"
echo "============================================================="

PID=$$
CLI_ADDRESS=10.203.1.1
ADDRESS=10.203.2.1

function finish {
	:
}

. ${srcdir}/ns.sh

${CMDNS1} ${top_builddir}/tests/avp-codec-freeradius ${ADDRESS}
if test $? != 0;then
	echo "Error in radcli2 avp codec / FreeRADIUS interoperability check"
	exit 1
fi

exit 0
