var searchData=
[
  ['a_2064_20bit_20accounting_20counter_0',['Reading a 64-bit accounting counter',['../radcli2-migration-examples.html#autotoc_md10',1,'']]],
  ['a_20realm_20to_20user_20name_20only_20when_20the_20caller_20didn_20t_20already_20supply_20one_1',['Appending a realm to User-Name only when the caller didn&apos;t already supply one',['../radcli2-migration-examples.html#autotoc_md9',1,'']]],
  ['a_20received_20avp_20list_2',['Reading a received AVP list',['../radcli2-migration-map.html#autotoc_md5',1,'']]],
  ['a_20repeated_20attribute_20reply_20message_20into_20one_20string_3',['Collecting a repeated attribute (Reply-Message) into one string',['../radcli2-migration-examples.html#autotoc_md13',1,'']]],
  ['a_20request_20accounting_20dae_4',['Sending a request / accounting / DAE',['../radcli2-migration-map.html#autotoc_md6',1,'']]],
  ['a_20text_20attribute_5',['radcli_avp_concat_str()/_by_num() &amp;ndash; join every occurrence of a text attribute',['../group__radcli2-avp-concat.html',1,'']]],
  ['a_20well_20known_20attribute_20in_20one_20call_6',['Looking up and reading a well-known attribute in one call',['../radcli2-migration-examples.html#autotoc_md12',1,'']]],
  ['accounting_20counter_7',['Reading a 64-bit accounting counter',['../radcli2-migration-examples.html#autotoc_md10',1,'']]],
  ['accounting_20dae_8',['Sending a request / accounting / DAE',['../radcli2-migration-map.html#autotoc_md6',1,'']]],
  ['add_20in_20one_20call_9',['radcli_avp_add_*_by_num() &amp;ndash; lookup-and-add in one call',['../group__radcli2-avp-by-num.html',1,'']]],
  ['already_20supply_20one_10',['Appending a realm to User-Name only when the caller didn&apos;t already supply one',['../radcli2-migration-examples.html#autotoc_md9',1,'']]],
  ['an_20avp_20list_20to_20send_11',['Building an AVP list to send',['../radcli2-migration-map.html#autotoc_md4',1,'']]],
  ['an_20rfc_208044_2064_20bit_20or_20ifid_20attribute_12',['Reading an RFC 8044 64-bit or ifid attribute',['../radcli2-migration-examples.html#autotoc_md11',1,'']]],
  ['and_20add_20in_20one_20call_13',['radcli_avp_add_*_by_num() &amp;ndash; lookup-and-add in one call',['../group__radcli2-avp-by-num.html',1,'']]],
  ['and_20features_14',['Protocols and features',['../index.html#autotoc_md14',1,'']]],
  ['and_20get_20in_20one_20call_15',['radcli_avp_get_*_by_num() &amp;ndash; lookup-and-get in one call',['../group__radcli2-avp-get-by-num.html',1,'']]],
  ['and_20reading_20a_20well_20known_20attribute_20in_20one_20call_16',['Looking up and reading a well-known attribute in one call',['../radcli2-migration-examples.html#autotoc_md12',1,'']]],
  ['api_17',['API',['../radcli2-migration.html',1,'Migrating from the legacy API'],['../index.html',1,'New API']]],
  ['api_20equivalent_20by_20design_18',['No new-API equivalent, by design',['../radcli2-migration-map.html#autotoc_md7',1,'']]],
  ['api_20mapping_19',['API mapping',['../radcli2-migration-map.html',1,'radcli2-migration']]],
  ['appending_20a_20realm_20to_20user_20name_20only_20when_20the_20caller_20didn_20t_20already_20supply_20one_20',['Appending a realm to User-Name only when the caller didn&apos;t already supply one',['../radcli2-migration-examples.html#autotoc_md9',1,'']]],
  ['attribute_21',['attribute',['../group__radcli2-avp-concat.html',1,'radcli_avp_concat_str()/_by_num() &amp;ndash; join every occurrence of a text attribute'],['../radcli2-migration-examples.html#autotoc_md11',1,'Reading an RFC 8044 64-bit or ifid attribute']]],
  ['attribute_20in_20one_20call_22',['Looking up and reading a well-known attribute in one call',['../radcli2-migration-examples.html#autotoc_md12',1,'']]],
  ['attribute_20reply_20message_20into_20one_20string_23',['Collecting a repeated attribute (Reply-Message) into one string',['../radcli2-migration-examples.html#autotoc_md13',1,'']]],
  ['attribute_20value_20pair_20handling_24',['Attribute-Value Pair Handling',['../group__radcli2-avp.html',1,'']]],
  ['authorization_20coa_20disconnect_25',['RFC 5176 dynamic authorization (CoA/Disconnect)',['../group__radcli-dae.html',1,'']]],
  ['avp_20list_26',['Reading a received AVP list',['../radcli2-migration-map.html#autotoc_md5',1,'']]],
  ['avp_20list_20to_20send_27',['Building an AVP list to send',['../radcli2-migration-map.html#autotoc_md4',1,'']]]
];
