var searchData=
[
  ['a_2064_20bit_20accounting_20counter_0',['Reading a 64-bit accounting counter',['../radcli2-migration-examples.html#autotoc_md10',1,'']]],
  ['a_20realm_20to_20user_20name_20only_20when_20the_20caller_20didn_20t_20already_20supply_20one_1',['Appending a realm to User-Name only when the caller didn&apos;t already supply one',['../radcli2-migration-examples.html#autotoc_md9',1,'']]],
  ['a_20received_20avp_20list_2',['Reading a received AVP list',['../radcli2-migration-map.html#autotoc_md5',1,'']]],
  ['a_20repeated_20attribute_20reply_20message_20into_20one_20string_3',['Collecting a repeated attribute (Reply-Message) into one string',['../radcli2-migration-examples.html#autotoc_md13',1,'']]],
  ['a_20request_20accounting_20dae_4',['Sending a request / accounting / DAE',['../radcli2-migration-map.html#autotoc_md6',1,'']]],
  ['a_20well_20known_20attribute_20in_20one_20call_5',['Looking up and reading a well-known attribute in one call',['../radcli2-migration-examples.html#autotoc_md12',1,'']]],
  ['accounting_20counter_6',['Reading a 64-bit accounting counter',['../radcli2-migration-examples.html#autotoc_md10',1,'']]],
  ['accounting_20dae_7',['Sending a request / accounting / DAE',['../radcli2-migration-map.html#autotoc_md6',1,'']]],
  ['already_20supply_20one_8',['Appending a realm to User-Name only when the caller didn&apos;t already supply one',['../radcli2-migration-examples.html#autotoc_md9',1,'']]],
  ['an_20avp_20list_20to_20send_9',['Building an AVP list to send',['../radcli2-migration-map.html#autotoc_md4',1,'']]],
  ['an_20rfc_208044_2064_20bit_20or_20ifid_20attribute_10',['Reading an RFC 8044 64-bit or ifid attribute',['../radcli2-migration-examples.html#autotoc_md11',1,'']]],
  ['and_20features_11',['Protocols and features',['../index.html#autotoc_md14',1,'']]],
  ['and_20reading_20a_20well_20known_20attribute_20in_20one_20call_12',['Looking up and reading a well-known attribute in one call',['../radcli2-migration-examples.html#autotoc_md12',1,'']]],
  ['api_13',['API',['../radcli2-migration.html',1,'Migrating from the legacy API'],['../index.html',1,'New API']]],
  ['api_20equivalent_20by_20design_14',['No new-API equivalent, by design',['../radcli2-migration-map.html#autotoc_md7',1,'']]],
  ['api_20mapping_15',['API mapping',['../radcli2-migration-map.html',1,'radcli2-migration']]],
  ['appending_20a_20realm_20to_20user_20name_20only_20when_20the_20caller_20didn_20t_20already_20supply_20one_16',['Appending a realm to User-Name only when the caller didn&apos;t already supply one',['../radcli2-migration-examples.html#autotoc_md9',1,'']]],
  ['attribute_17',['Reading an RFC 8044 64-bit or ifid attribute',['../radcli2-migration-examples.html#autotoc_md11',1,'']]],
  ['attribute_20in_20one_20call_18',['Looking up and reading a well-known attribute in one call',['../radcli2-migration-examples.html#autotoc_md12',1,'']]],
  ['attribute_20reply_20message_20into_20one_20string_19',['Collecting a repeated attribute (Reply-Message) into one string',['../radcli2-migration-examples.html#autotoc_md13',1,'']]],
  ['avp_20list_20',['Reading a received AVP list',['../radcli2-migration-map.html#autotoc_md5',1,'']]],
  ['avp_20list_20to_20send_21',['Building an AVP list to send',['../radcli2-migration-map.html#autotoc_md4',1,'']]]
];
